import { cookies } from "next/headers";
import Header from "@/components/header";

import { ThemeProvider } from "@/shadcn/lib/theme-provider";
import { Toaster } from "@/shadcn/ui/toaster";

import "./globals.css";

import { AuthTokenProvider } from "@/context/AuthTokenProvider";

export const metadata = {
	title: process.env.NEXT_PUBLIC_PROJECT_NAME,
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	const access_token = cookies().get("access_token")?.value;

	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<ThemeProvider defaultTheme="dark" attribute="class">
					<AuthTokenProvider access_token={access_token ?? ""}>
						<Header />
						{children}
						<Toaster />
					</AuthTokenProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
